name: SuperWhisper
options:
  bundleIdPrefix: com.superwhisper
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.0.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic
    PRODUCT_BUNDLE_IDENTIFIER: com.superwhisper.app
    MARKETING_VERSION: "1.0.1"
    CURRENT_PROJECT_VERSION: "202602172346"
    INFOPLIST_FILE: SuperWhisper/Info.plist
    CODE_SIGN_ENTITLEMENTS: SuperWhisper/SuperWhisper.entitlements
    ENABLE_HARDENED_RUNTIME: false

targets:
  SuperWhisper:
    type: application
    platform: macOS
    sources:
      - path: SuperWhisper
        excludes:
          - "**/*.entitlements"
          - "Info.plist"
    dependencies:
      - package: Sparkle
    settings:
      base:
        INFOPLIST_FILE: SuperWhisper/Info.plist
        CODE_SIGN_ENTITLEMENTS: SuperWhisper/SuperWhisper.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: false

  SuperWhisperTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: SuperWhisperTests
    dependencies:
      - target: SuperWhisper
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SuperWhisper.app/Contents/MacOS/SuperWhisper"
        BUNDLE_LOADER: "$(TEST_HOST)"
